### ISSUE TITLE
Error: feature file use fullwidth font characters(chinese) 

### ISSUE THREAD

**Issue by gonex45** [DATA-DOG/godog#101]
i use chinese in feature file

```
Feature: 登入
  遊戲管理系統登入驗證

  Scenario: 成功登入
    Given 正確的帳號及密碼
    When 按下登入
    Then 回傳成功狀態碼
      """
      1
      """
```

Console output：
`panic: runtime error: index out of range`

`github.com/DATA-DOG/godog/fmt.go:412 +0xbe3`

fmt.go:412
`w = string(unicode.ToLower(rune(w[0]))) + w[1:]`

i change to 
```
if len(w) != 0 {
    w = string(unicode.ToLower(rune(w[0]))) + w[1:]
}
```
it works

Is there a better way?

**Comment by l3pp4rd** [comment]
Hi, thanks for providing a feature sample, should be resolved. Guess you usually stumble on unicode support issues for chinese, hopefully we will improve with go.
