### ISSUE TITLE
Gopher inquiry

### ISSUE THREAD

**Issue by jaysonesmith** [DATA-DOG/godog#102]
Hey, folks! 

I've tried emailing info@data-dog.co.uk but haven't received any info. I'm looking to acquire some stickers of the godog gopher for myself, teammates, etc. I put in an order with StickerMule for some 4"x4" stickers using the logo that's in the readme, but it's not high enough quality. 

Would it be possible to send me a version of the godog gopher in a larger resolution and at 300dpi please? (Ideally as a vector if possible!)

Thanks!

**Comment by l3pp4rd** [comment]
Hi @jaysonesmith I've asked our designer to try and find it, will attach it if it is found ;)

**Comment by jaysonesmith** [comment]
@l3pp4rd Woot thank you!!

**Comment by l3pp4rd** [comment]
sorry, but our designer could not find it anymore, it was made quite some time ago.. there is a little bigger size image stored in history before https://github.com/DATA-DOG/godog/commit/afbb70017ff6a7f12de96bab610e95c312098674 if that helps ;)

**Comment by jaysonesmith** [comment]
@l3pp4rd Thanks! I had seen the earlier version as well. Would you be open to my recreating the logo in higher quality while staying faithful to the original? Happy to share it with the project too!

**Comment by l3pp4rd** [comment]
sure, no problem with that, you can go as far as your imagination takes you :)
