### ISSUE TITLE
Feature background

### ISSUE THREAD

**Issue by stiks** [DATA-DOG/godog#105]
Correct me if I'm wrong, but if I set Background inside Feature, it should be running once. It's look like Background is running with every Scenario, except first one.

![screen shot 2017-10-23 at 22 59 56](https://user-images.githubusercontent.com/827083/31915324-f1f0d574-b845-11e7-9dee-2fde463c613b.png)

Example:
```
Feature: Manage company contacts

  In order to test application behavior
  As a client software developer
  I need to be able to manage company contacts

  Background:
    Given there are Users with the following details:
      | id | username | email          | password |
      | 1  | peter    | peter@test.com | testpass |
      | 2  | john     | john@test.org  | johnpass |
      | 3  | tim      | tim@blah.net   | timpass  |
    And I set header "Content-Type" with value "application/json"

  Scenario: Can create new contact
    When I send a "POST" request to "/contacts" with body:
      """
      {
        "username": "peter@test.com",
        "password": "testpass"
      }
      """
    Then the response code should be 200

  Scenario: Can login with new registered user details
     And I send a "GET" request to "/contacts"
    Then the response code should be 200
     And the response should contain json:
      """
      {
        "id": "2",
        "email": "gary@test.co.uk"
      }
      """
```

**Comment by l3pp4rd** [comment]
Hi, background must run for every scenario. Usually background is used to set, reset some state for every scenario. and best practice is to reset whole state including the database for every scenario. in Golang I usually start and rollback transaction if it is an sql database, see [txdb](https://github.com/DATA-DOG/go-txdb) as an example for such behavior.

**Comment by stiks** [comment]
I've been using same scenarios with Behatch (PHP) and it's working a different way

**Comment by l3pp4rd** [comment]
official cucumber in PHP is **behat** not behatch and it runs backgroud for every scenario the same way as all other cucumber implementations.
