### ISSUE TITLE
Coloring of failed scenario in Table

### ISSUE THREAD

**Issue by heynemann** [DATA-DOG/godog#106]
Hi,

First thank you very much for a great library. When I'm running my test with progress formatter, I get this:
```
.................
F 18


--- Failed steps:

    Then  the user has 333 gems # test/test.feature:14
      Error: expected user to have 333 gems, but user in DB has 768 gems
```

While if I run it in pretty, I get this:

```
Feature: Claiming a piggy-bank

  Background: 
    Given the server is up
    And an user exists with id "fb9e28db-3318-4b4b-a893-bb642cfe5245"

  Scenario Outline: Some stuff happen
    Given the user has <initial> gems
    When the user stores <gems> gems
    Then the user has <total> gems

    Examples: 
      | initial | gems | total |
      | 347   | 435   |  782  |
      | 333  | 435   |  333  |

2 scenarios (1 passed, 1 failed)
18 steps (17 passed, 1 failed)
3.933355867s
```

I intentionally omitted some steps. The point here is that in the second one, both lines in the examples are green, even though the second one failed.

Am I missing something?

**Comment by l3pp4rd** [comment]
thanks for reporting and a sample code, will have a look ;) most likely a bug in formatter

**Comment by l3pp4rd** [comment]
Hm, actually that **F** you see in a new line is a failed step indicator next to step number **18**. it is just strange that it is in a new line

**Comment by l3pp4rd** [comment]
![2017-10-26-144341](https://user-images.githubusercontent.com/132389/32051120-1953319e-ba5c-11e7-9bff-6d17f77b3b64.png)

**Comment by l3pp4rd** [comment]
cannot reproduce it, maybe there is more context?

![2017-10-26-145840](https://user-images.githubusercontent.com/132389/32051648-2c817a76-ba5e-11e7-9050-eb21497a2221.png)

``` go
package main

import (
	"fmt"

	"github.com/DATA-DOG/godog"
)

func FeatureContext(s *godog.Suite) {
	s.Step(`^passing$`, func() error {
		return nil
	})
	s.Step(`^failing$`, func() error {
		return fmt.Errorf("failed")
	})
	s.Step(`^outcome (\d+)$`, func(c int) error {
		if c == 5 || c == 333 {
			return fmt.Errorf("fail on total %d", c)
		}
		return nil
	})
	s.Step(`^action (\d+)$`, func(c int) error {
		return nil
	})
	s.Step(`^context (\d+)$`, func(c int) error {
		return nil
	})
}
```

**Comment by l3pp4rd** [comment]
are you using latest godog version from master branch?

**Comment by heynemann** [comment]
Yes. Just checked. I am returning an error with fmt.Errorf when a condition fails, yet the line shows green.

**Comment by heynemann** [comment]
The thing I'm doing different is I'm running with a testfile:

```
package features

import (
	"flag"
	"os"
	"testing"

	"github.com/DATA-DOG/godog"
)

var focus = flag.Bool("focus", false, "focus feature")

func TestMain(m *testing.M) {
	flag.Parse()
	opts := godog.Options{
		Format: "pretty",
		Paths:  []string{"."},
	}
	if *focus {
		opts.Tags = "focus"
	}
	status := godog.RunWithOptions("blockcraft", func(s *godog.Suite) {
		FeatureContext(s)
	}, opts)

	if st := m.Run(); st > status {
		status = st
	}
	os.Exit(status)
}
```

**Comment by l3pp4rd** [comment]
could you try to reproduce it with my sample of basic step definitions? like just fail it on certain value

**Comment by heynemann** [comment]
Not sure what happened, but I can't reproduce it anymore. :( Sorry to bother...

**Comment by l3pp4rd** [comment]
hm, that is strange, if it pops up again, reopen please ;)

**Comment by heynemann** [comment]
Thanks!
