### ISSUE TITLE
Examples in background block not supported

### ISSUE THREAD

**Issue by JeanMertz** [DATA-DOG/godog#114]
This seems to cause an error, while I believe it's valid Gherkin:

```gherkin
Feature: Correctly test this

  Background: Prepare tests
    Given the "<client>" client is used
    And the correct config is used
    Examples:
      | client  |
      | client1 |
      | client2 |
```

```
features/clients.feature - Parser errors:
(5:5): expected: #EOF, #TableRow, #DocStringSeparator, #StepLine, #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got '    Examples:'

```

**Comment by JeanMertz** [comment]
In fact, looking into this, It looks like this is _not_ valid. As examples are only supported in a "scenario outline". That's too bad. I'll keep this open in case you _do_ want to support this, but feel free to close if this is working as intended.

**Comment by l3pp4rd** [comment]
Hi, godog will always use official gherkin implementation and we will not implement something different, if you think it makes sense to have such support in gherkin, the issue should be opened in cucumber repository, not here. But I think there were such considerations already, so you may just google for it to see the answers and reasoning behind it.
