### ISSUE TITLE
go 1.10

### ISSUE THREAD

**Issue by alexfalkowski** [DATA-DOG/godog#115]
When I install and run it

```
godog --format=pretty --strict

open /var/folders/zx/2x3z8x1d5114hvfdd89pvcd40000gn/T/go-build144155201/.../_test/_testmain.go: no such file or directory
```

**Comment by alexfalkowski** [comment]
Compiling this src

```
λ  godog master ✗ go build -o godog cmd/godog/main.go
λ  godog master ✗ ./godog
open /var/folders/zx/2x3z8x1d5114hvfdd89pvcd40000gn/T/go-build919377817/github.com/DATA-DOG/godog/_test/_testmain.go: no such file or directory
```

**Comment by l3pp4rd** [comment]
Hi, something may have changed in go build process in 1.10. will need to check this

**Comment by l3pp4rd** [comment]
yes, the toolchain has changed for package compilation, will need to adapt this to support go 1.10. for now you can run godog from [TestMain as described here](https://github.com/DATA-DOG/godog#running-godog-with-go-test)

**Comment by jaysonesmith** [comment]
@l3pp4rd If you've got ideas on how you'd plan to do the change, I'd be happy to work on it. :)

**Comment by Dogild** [comment]
I propose a fix here https://github.com/DATA-DOG/godog/pull/116, not sure if it's the way to do it. But it can help till a final solution is released
