### ISSUE TITLE
Specify file using go test

### ISSUE THREAD

**Issue by nerde** [DATA-DOG/godog#120]
We have a project running Godog via:

`go test -v -tags=features -cover ./my_package`

Is it possible to specify which feature file(s) I want to run using my `go test` command?

**Comment by alexfalkowski** [comment]
According to the [documentation](https://golang.org/pkg/testing/#hdr-Subtests_and_Sub_benchmarks) we have `go test -run` not sure if this works.

**Comment by nerde** [comment]
I tried several combinations of `go test -run`, all I get is:

```
?   	github.com/my/project/my_package	[no test files]
```

**Comment by l3pp4rd** [comment]
Hi, you may specify features to run by using `godog --tags=wip` command. if you integrate it in `go test` then you need to capture the flags manually in your `TestMain` as described [here](https://github.com/DATA-DOG/godog#running-godog-with-go-test) 

`godog.Options` can contain all the configuration you need to filter features, by default these are populated from flags using `godog` command. So when integrating with go test, I suggest to use default flags or other ways to set these options the way you need.

It would be hard and with side effects if godog would try to temper default flags `go test` is using. I may explore some options later on, but so far you need to modify them the way you see fit.

**Comment by l3pp4rd** [comment]
actually since we can prefix flags like `go test` does, support was added to bind godog flags to existing flagset, see [the example](https://github.com/DATA-DOG/godog#running-godog-with-go-test)

**Comment by nerde** [comment]
@l3pp4rd thank you for the help! We are using build tags to isolate features from regular unit tests. Also we have our go files in a subfolder (this app has several packages), so this is the regular command:

```
go test -v -tags=features ./...
```

It works fine from the root path as well as from the subfolder. I used your example to tweak my `TestMain` and read godog flags, but when I run:

```
go test -v -tags=features --godog.tags=wip ./...
```

I get `no Go files in /my/project/path`. If I go inside the subfolder and run it, it works perfectly. Here's my `TestMain`:

```
var opt = godog.Options{Output: colors.Colored(os.Stdout)}

func init() {
	godog.BindFlags("godog.", flag.CommandLine, &opt)
}

func TestMain(m *testing.M) {
	flag.Parse()
	opt.Strict = true
	opt.Paths = []string{"features"}

	status := godog.RunWithOptions("godog", func(s *godog.Suite) {
		godog.SuiteContext(s)
		ContextNumberOne(s)
		ContextNumberTwo(s)
	}, opt)

	if st := m.Run(); st > status {
		status = st
	}

	os.Exit(status)
}
```

Any idea why when I add `godog.tags` into the mix Go is not able to find my test files in subfolders?

**Comment by l3pp4rd** [comment]
I do not think the error `no Go files in /my/project/path` comes from godog, if I run `go test -v ./...` inside godog package, it runs all tests including godog features in all the packages found, though if you add custom non go test flags, then the `go test` will run only in the root directory. in general godog should be run from the package root you are testing. though even test coverage can only work per single package
