### ISSUE TITLE
Scenario name

### ISSUE THREAD

**Issue by papitoio** [DATA-DOG/godog#125]
How to get scenario name on afterScenario?

Please.

**Comment by l3pp4rd** [comment]
the interface passed as an argument is either Scenario or ScenarioOutline https://github.com/DATA-DOG/godog/blob/master/gherkin/ast.go#L41-L50 was mentioned in the [godoc](https://github.com/DATA-DOG/godog/blob/master/suite.go#L195) should read it before asking
