### ISSUE TITLE
Can godog be run against a binary

### ISSUE THREAD

**Issue by AmitKumarDas** [DATA-DOG/godog#126]
I have just started experimenting with godog.
Is it possible to run godog xyz.feature against an already built src code?

**Comment by l3pp4rd** [comment]
yes, it works in similar way like go test

![2018-04-20-202859](https://user-images.githubusercontent.com/132389/39065152-88aabf3c-44d9-11e8-924d-2db877611fb6.png)

you can build the binary:

``` sh
godog -o binary
./binary -f progress feature/path
```

**Comment by AmitKumarDas** [comment]
Thanks @l3pp4rd I am yet to try this out.
I am closing it for the timebeing.

**Comment by jakubknejzlik** [comment]
Just for the sake of completeness...tried and works like a charm! Thanks @l3pp4rd .
For others interested, you can check the specific commands: https://github.com/jakubknejzlik/godog-sql/blob/master/Dockerfile
