### ISSUE TITLE
Public API to get reference to a Formatter

### ISSUE THREAD

**Issue by zeeke** [DATA-DOG/godog#130]
Hi,

I'm trying to make a custom `godog.Formatter` that wraps the behavior of another formatter.
Unluckily there is no public API to get the reference to a predefined one and it brings to a very ugly copy and paste work.

I know that keeping the set of public APIs as small as possible increases project's maintainability, but it would be useful to get [`findFmt(...)`](https://github.com/DATA-DOG/godog/blob/master/fmt.go#L56) public.

What do you think about it?

**Comment by l3pp4rd** [comment]
Hi, at some point I was planning to refactor formatters. If the interface is exposed to public that would introduce backward incompatibility later. since godog is yet not 1.0 and in readme it is clearly stated that there are expected BC changes, it is considerable to make something public. tell me exactly why that function being public would help you to create custom formatter. I do not think that copying the code, would be a bad choice.

**Comment by zeeke** [comment]
If the `findFmt(...)` function was public I would be able to make a composite formatter that writes to multiple backend formatters, i.e. one that writes to console and one that writes cocumber to a file.
It's not of vital importance, I can achieve the same result by copying code.

BTW, `godog.Formatter` interface is not that bad (IMO) and functions `godog.FormatterFunc`, `godog.AvailableFormatters` are already public.

You can have a think about it.

**Comment by l3pp4rd** [comment]
OK, makes sense to have it exposed

**Comment by l3pp4rd** [comment]
@zeeke could you show the example code you used to combine formatters, that could be useful in readme or examples

**Comment by zeeke** [comment]
Hi, I combined formatters using the following pattern:

```go

func init() {
	godog.Format("cucumber-progress", "Combined Progress and Cucumber", cucumberProgressFunc)
}

func cucumberProgressFunc(suite string, out io.Writer) godog.Formatter {
	progress := godog.FindFmt("progress")(suite, out)
	file, _ := os.Create("cucumber.json"))
	cucumber := godog.FindFmt("cucumber")(suite, file)
	return &combinedFormatter{
		delegates: []godog.Formatter{
			progress,
			cucumber,
		},
	}
}

type combinedFormatter struct {
	delegates []godog.Formatter
}

func (j *combinedFormatter) Feature(feature *gherkin.Feature, path string, c []byte) {
	for _, delegate := range j.delegates {
		delegate.Feature(feature, path, c)
	}
}

func (j *combinedFormatter) Defined(step *gherkin.Step, stepDef *godog.StepDef) {
	for _, delegate := range j.delegates {
		delegate.Defined(step, stepDef)
	}
}

// ... so on for the other methods
```

I can provide a PR to add the combined formatter to the library, if needed.

**Comment by inluxc** [comment]
How did you import the custom formater into the godog? Did you build your own godog ?
