### ISSUE TITLE
Support tags on example tables of scenario outlines

### ISSUE THREAD

**Issue by agajdosi** [DATA-DOG/godog#133]
I would like to control via tags which values scenario outline use from examples table. For example, having two variant tables tagged `@en-gb` and `@en-us` for testing language variants, or being able to expand the list of test cases, for example `@nightly` tagged table containing few cases and then `@release` tagged table containing much more cases. Same feature got implemented in `cucumber-js`: https://github.com/cucumber/cucumber-js/issues/305.

Trying the following does not work using Godog v0.7.6:

```
  Scenario Outline: Setting values in wrong range or format
     Then executing "minishift config set <property> <value>" fails

  @minishift-only
  Examples: Wrong values for unit based keys (Minishift)
    | property        | value     |
    | disk-size       | 0         |
    | disk-size       | 25000.78  |

  @cdk-only
  Examples: Wrong values for unit based keys (CDK)
    | property        | value     |
    | disk-size       | -0        |
    | disk-size       | 25000.77  |
```

**Comment by l3pp4rd** [comment]
Hi @agajdosi will have to check how the current filtering is performed, but most likely it should not be difficult to filter example tables.

**Comment by agajdosi** [comment]
Thanks @l3pp4rd.
