### ISSUE TITLE
using `myproject_test` for tests.

### ISSUE THREAD

**Issue by llonchj** [DATA-DOG/godog#137]
I have a package, let's say named myproject, and the test files use `package myproject_test`.
Under this case scenario, i get 

failed to compile testmain package: exit status 2 - output: /var/folders/x4/s1l6gz3x7b5fqvbnbfj80zn40000gn/T/go-build582670283/b001/_testmain.go:5:2: can't find import: "_/Users/myuser/myproject"

I am using go mod and myproject is outside GOPATH and guess the issue might be reproducible with myproject inside GOPATH.

**Comment by l3pp4rd** [comment]
hm, that one has a very interesting compilation process when a test suffix is given to a package. it will take some time to implement this correctly

**Comment by l3pp4rd** [comment]
in case if it still does not work on go1.10 or later, let me know
