### ISSUE TITLE
convert data table to struct

### ISSUE THREAD

**Issue by matheussilva97** [DATA-DOG/godog#140]
It will be useful a way to convert the data table of feature to struct in a simple and fast way.

Example:
Data Table:
```
  | value 1  | value 2 | result |
  |  5         |  10     |   15       |
```

Struct:
```
type Table struct {
	Value1 string `godog:"value 1"`
	Value2 string `godog:"value 2"`
	Result string `godog:"result"`
}
```

usually:

```
 var t Table 
 gherkin.ParseDataTable(dataTable, &t)
 fmt.Println(t.Value1) // print 5
 fmt.Println(t.Value2) //print 10
 fmt.Println(t.Result)  //print 15
```

**Comment by l3pp4rd** [comment]
Hi, godog does not provide any additional features to parse DocStrings or Tables. You can easily implement it yourself, based on the needs you have. create a method like `table(src *gherkin.Table, dst *myStruct) error` basically you can create any helper methods you like

**Comment by matheussilva97** [comment]
perfect, I will do this! :D

**Comment by l3pp4rd** [comment]
there was something like that in https://github.com/rdumont/assistdog not sure if that is similar what you need

**Comment by rolandroos** [comment]
Whereas it may work for some cases, It did not for me.
I need more then 2 props/fields per struct.

This generic type peace of (complex code) worked:

    type Ptr[T any] interface {
	*T
    }

    type StructFactory[T Ptr[U], U any] struct{}

    func (f StructFactory[TPtr, TType]) CreateArrayFromTable(godogTable *godog.Table) []TPtr {

	var as []TPtr

	var rows []*messages.PickleTableRow = godogTable.Rows

	var columns *messages.PickleTableRow = rows[0]
	for _, rowPtr := range rows[1:] {

		var someStruct TType

		//set props
		for indexOfCells, nameStrOfProp := range columns.Cells {
			var propname string = nameStrOfProp.Value //e.g Cts, App, Code, ...
			var propValue string = rowPtr.Cells[indexOfCells].Value
			 
    reflect.ValueOf(&someStruct).Elem().FieldByName(propname).Set(reflect.ValueOf(propValue))
		}
		as = append(as, &someStruct)
	}
	return as
    }

And then:

    | Ctx   | App  | Code |
    | 1     | gnss | 5    |
    | 1     | gnss | 500  |
    
    func testParam(ctx context.Context, dogTable *godog.Table) error {
        type Item struct {
		Ctx  string
		Code string
		App  string
        }

        itemFact := StructFactory[*Item, Item]{}
       all := itemFact.CreateArrayFromTable(dogTable)
