### ISSUE TITLE
GO1.11 : go test -o NUL fails on Windows

### ISSUE THREAD

**Issue by Pykselle** [DATA-DOG/godog#142]
I put it here for information, in case somebody else encounters this issue :

On Windows and Go1.11, I am not able to launch godog tests with the "godog" command anymore.

This is apparently due to this issue in Go1.11 : https://github.com/golang/go/issues/28035

The error message I get is the following :

```
$ godog  
failed to compile tested package: qa, reason: exit status 1, output: WORK=C:\Users\CBONNA~1\AppData\Local\Temp\go-build279225422  
go test gitlab.prod.saas.lan/neo/qa.test: build output "C:\\Users\\cbonnafous\\go\\src\\gitlab.prod.saas.lan\\neo\\qa\\NUL" already exists and is not an object file
```

To bypass this issue, I have to add a TestMain function as explained in the FAQ (https://github.com/DATA-DOG/godog#running-godog-with-go-test), and launch the tests with "go test"

**Comment by l3pp4rd** [comment]
made it like in previous go versions, to generate a file in temp directory. this should now work on windows too

**Comment by Pykselle** [comment]
Great, thanks !
