### ISSUE TITLE
Godog crashes on incomplete feature file

### ISSUE THREAD

**Issue by christianhujer** [DATA-DOG/godog#145]
When a feature file is incomplete, godog crashes.

Steps to reproduce:
1. Setup tests with godog.
2. Create a feature file with the following content:
```
Feature: foo
  Scenario: bar
```

Expected behavior: Godog runs and says there are no tests to execute.
Actual behavior: Godog crashes with `panic: strings: negative Repeat count`

**Comment by l3pp4rd** [comment]
thanks for reporting
