### ISSUE TITLE
Print effective seed if randomized with -1

### ISSUE THREAD

**Issue by christianhujer** [DATA-DOG/godog#146]
When running the tests randomized, and setting the seed to -1, Godog says it uses a random seed. In the end, Godog prints the following message:

    Randomized with seed: -1

Godog should print the actual seed that was chosen, so that pipelines can run with seed `-1`, but developers will know which seed to chose to reproduce problems on their machines.

**Comment by l3pp4rd** [comment]
thanks for reporting, indeed, even when specifying it directly through an option, this had to be checked in runner
