### ISSUE TITLE
Suite.BeforeStep() called before parameters are extracted from step

### ISSUE THREAD

**Issue by agajdosi** [DATA-DOG/godog#147]
I am trying to implement something which could be called "Scenario Variables" so one could set variable `VARIABLE_NAME` in code in BeforeFeature(), or with special steps like `set variable "USERNAME" to output of "whoami"` and then one could refer to the variable in any step using `$(VARIABLE_NAME)`.

As I want to have this functionality on all steps, I tried the way of using BeforeStep() which seemed quite ideal:

```
	s.BeforeStep(func(this *gherkin.Step) {
		this.Text = util.ProcessVariables(this.Text)
	})
```

With this change it all looks good in the Godog output, the variables defined in features get replaced by the values and the value is printed to the console:

```
In feature:
  Scenario: Setting iso-url key to a non existing path                                                                                                # features/test.feature:14
    When executing "minishift config set iso-url $(TEST_HOME)/non-existing.iso" fails
----
In the terminal, when feature is run:
  Scenario: Setting iso-url key to a non existing path                                                                                                # features/test.feature:14
    When executing "minishift config set iso-url file:///home/agajdosi/golang/src/github.com/minishift/minishift/out/test-run/non-existing.iso" fails
```

It looks like exactly what I wanted. But...

Problem is that the functions which implements the individual steps do not get the substituted values as matched parameters, instead of value they get non substituted `$(VAR_NAME)`. This leads me to thinking that matching of the step is being done before the BeforeStep() is run, which seems to me as a bug.

**Comment by agajdosi** [comment]
Moving "run before step handlers" in `suite.go` from the end of runStep() to its begging - before the s.matchStep() fixed the problem completely:

```
func (s *Suite) runStep(step *gherkin.Step, prevStepErr error) (err error) {

	// run before step handlers
	for _, f := range s.beforeStepHandlers {
		f(step)
	}

	match := s.matchStep(step)
	s.fmt.Defined(step, match)
[...]
```

**Comment by l3pp4rd** [comment]
Hi @agajdosi I do not see the reason why it could not be moved there, will close it shortly with a commit.

**Comment by agajdosi** [comment]
@l3pp4rd That was hilariously swift, thanks!

**Comment by rolandmkunkel** [comment]
@agajdosi Did you create an upstream patch for your placeholder feature? I would be interested in using this functionality as well
