### ISSUE TITLE
Godog installation fails

### ISSUE THREAD

**Issue by SkinyMonkey** [DATA-DOG/godog#149]
With go mod:

```
$>go get github.com/DATA-DOG/godog/cmd/godog
go: finding github.com/DATA-DOG/godog/cmd/godog latest
go: finding github.com/DATA-DOG/godog/cmd latest
```

**Comment by l3pp4rd** [comment]
Hi, what was confusing about it, maybe I need to add something in the README ?

**Comment by SkinyMonkey** [comment]
Hi, i'm sorry, somehow I opened a second issue with the same problem but more details : #150 

Thank you for your time and attention
