### ISSUE TITLE
Testing subpackages

### ISSUE THREAD

**Issue by robotlovesyou** [DATA-DOG/godog#152]
I'm sure I'm being stupid here but I'm struggling to see how I test subpackages.

If I have a project `my_project` with package `documents` and `files` I seem to have to run godog from the subpackages themselves. If I try to run it from the `my_project` package with
```
godog documents
``` 
for example, it doesn't find the FeatureContext exported function in the documents package and instead dumps out the step stubs I should create to the console.

What I want to be able to do is output a single executable which will run tests against all my sub-packages. Can I do this?

**Comment by l3pp4rd** [comment]
Hi, yes, you are not mistaken or stupid. `godog` uses `go` to compile `test` files and go supports testing only single package once, when you run `go test ./...` it would run each subpackage separately. `godog` does not have such recursive command and though, it would only be useful if you would compile each package tests together and go does not support that. So in general, godog should be mostly used to test  packages where your main func is (an entry point) to do user behavior driven tests or separately per package in isolation where it tests only single package.

**Comment by robotlovesyou** [comment]
Ah OK. Yes, I was hoping that since you say `Godog does not intervene with the standard go test command behavior` that you might offer a different behaviour. Never mind. Thanks for the prompt feedback.

**Comment by l3pp4rd** [comment]
yes, sadly we cannot import other test packages in one being tested, if we could, then that could be possible to make such behavior.
