### ISSUE TITLE
How to run Godog in another testing framework. 

### ISSUE THREAD

**Issue by aaronmcohen** [DATA-DOG/godog#153]
I am trying to run GODOG inside of the [Operator-sdk test framework](https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/writing-e2e-tests.md). Now the problem is it  requires a test main entry point and hijacks the test suite.
```go
package e2e

import (
    "testing"

    f "github.com/operator-framework/operator-sdk/pkg/test"
)

func TestMain(m *testing.M) {
    f.MainEntry(m)
}
```

To get around this I embed GODOG inside an individual test.
```go
var opt = godog.Options{
	Output: colors.Colored(os.Stdout),
	Format: "pretty",
}

func TestBDD(t *testing.T) {
	flagSet := flag.FlagSet{}
	godog.BindFlags("godog..", &flagSet, &opt)
	status := godog.RunWithOptions("godogs", func(suite *godog.Suite) {
		steps.DeploymentFeatureContext(suite)
	}, opt)
	if status > 0 {
		t.Fail()
	}
}
```
Now even though I binded godog with an empty flag set it still inherits the parent framework's command line arguments.
>flag provided but not defined: -namespacedMan

What is the proper way to run GODOG from another testing framework?

**Comment by l3pp4rd** [comment]
Hi, it is sad that other frameworks think they are the only frameworks. anyway you may bind godog flags to default command line options, there was such example in readme.

``` go
var opt = godog.Options{
	Output: colors.Colored(os.Stdout),
	Format: "progress", // can define default values
}

func init() {
	godog.BindFlags("godog.", flag.CommandLine, &opt)
}
```
