### ISSUE TITLE
Cucumber JSON report not getting Docstring nor Datatable from feature file

### ISSUE THREAD

**Issue by axcosta** [DATA-DOG/godog#157]
Trying to use godog with cucumber-html-reporter but generated JSON report is not getting Docstring nor Datatable from feature file. Anyone else experimenting the same?

**Comment by l3pp4rd** [comment]
Hi, yes seems like the table data is not in the output

**Comment by l3pp4rd** [comment]
Maybe you want to contribute that change?

**Comment by axcosta** [comment]
I certainly want but don't know if I can (because of time and effort and knowledge).

**Comment by l3pp4rd** [comment]
I suggest for you to try, it may take a while for me to find time. the formatter code needs an update to build table [data for json here](https://github.com/DATA-DOG/godog/blob/master/fmt_cucumber.go#L281) at the moment it only checks if it is DocString and manages that only, not the table.

**Comment by l3pp4rd** [comment]
should be available now in master, in case if not, just reopen
