### ISSUE TITLE
ability to define steps belong to scenario

### ISSUE THREAD

**Issue by nvcnvn** [DATA-DOG/godog#177]
Sorry for posting the question here, I'm having some trouble with my test code structure.
For example, given 2 features, each feature have only 1 scenarios with 1 similar step:

_registration.feature_
```
Feature: Registration
    Scenario: simple registration
        Given a valid profile
        When a user send a registration request
        Then we must records the profile
            And returns "OK" status code
            And returns trial status as "true"
```
_chat.feature_
```
Feature: Chat
    Scenario: simple chat
        Given a valid message
        When a user send a chat request
        Then we must records the chat
            And returns "OK" status code
```
Right now, I need to  change the text to make all the steps in my suite different  (the `returns "OK" status code`)

If we have away to:
```
s.Step("returns 'OK' status code", registrationTestSuite.checkStatus)
s.Step("a valid profile", registrationTestSuite.generateValidProfile)
s.Step("a user send a registration request", registrationTestSuite.sendRegistrationRequest)
s.Step("we must records the profile", registrationTestSuite.checkProfileInDB)
s.Step("returns trial status as 'true'", registrationTestSuite.checkTrialStatus)

s.Step("returns 'OK' status code", chatTestSuite.checkStatus)
s.Step("...", chatTestSuite.)
s.Step("...", chatTestSuite.)
s.Step("...", chatTestSuite.)
s.Step("...", chatTestSuite.)
```
It should be clean and easier to arrange the test code.
Maybe by some how define which scenario the step belong to?

**Comment by l3pp4rd** [comment]
Hi, the whole reason for step definitions is to abstract the behavior. if you have two exact steps, means they perform exact behavior, if that is not the case, you need to change and add a different step. Step definitions matches steps, they do not have any background to which feature or scenario ir belongs to. 

If you are testing a HTTP API, it would make sense to name step as `the response code should be "200"` or something like it, it should be the same step for all of the cases where you expect a response with some status. For different responses, you may have `response should contain json:` or similar.
For instance, these steps in your example:

``` gherkin
        Then we must records the profile
            And returns "OK" status code
            And returns trial status as "true"
```

could be changed to just one: `Then the user should be on "trial"` in case you have some behavioral exceptions for such case. But in general, the point is, to create as few readable step definitions as reasonable. Too many of them will lead to many refactorings.

**Comment by nvcnvn** [comment]
But then I found it make thing more difficult to isolate scenarios.
```feature
    Scenario: registration
        Given a valid profile
        When user send the request
        Then we must records the profile
            And returns "OK" status code
            And returns trial status as "true"

    Scenario: chat
        Given a valid chat message
        When user send the request
        Then we must records the chat
            And returns "OK" status code
```
With that way, I need to implement something like:
```go
type mySuite struct {
    request interface{}
    response interace{}
    statusCode int
}

func (s *mySuite) aValidProfile() error {
    s.request = NewProfile()
}

func (s *mySuite) aValidChatMessage() error {
    s.request = NewChatMessage()
}

func (s *mySuite) userSendTheRequest() error {
    s.response, s.statusCode = sendRequest(s.request)
}

func (s *mySuite) weMustRecordsTheProfile() error {
    return checkDBFor(s.request.(Profile))
}

func (s *mySuite) weMustRecordsTheChat() error {
    return checkDBFor(s.request.(ChatMessage))
}

func (s *mySuite) andRetrunStatusCode(code int) error {
    return errorIfNotEqual(s.statusCode==code)
}
```
Then use mySuite's methods to define the steps.

With the `mySuite`, I introduced a global state across all scenarios and features, think will get more cumbersome if I want to enable concurrency.
Also, with more and more scenarios, the `mySuite` will grow with more fields.
In the end the code to implement the test will end up like using function and access global variables.

I'm not sure if we have a better way to handle it.

**Comment by l3pp4rd** [comment]
Godog runs every scenario on a separate Suite instance in isolation.
It means that your `mySuite` instance will run one scenario at the time, though the state you have in that mySuite, should be reset in BeforeScenario hook. Godog at the moment only runs separate features in parallel, not the scenarios. So as far as your example is considered, you will be able to run features concurrently as long as your database will support it, for instance if you have two features creating same user at the same time, then you may have an issue. In such cases I use [txdb](https://github.com/DATA-DOG/go-txdb) to isolate it within a separate transaction. Though, this will only work on RDBMS

**Comment by nvcnvn** [comment]
Thanks you for your quick and helpful reply.

If I want to run that 2 features concurrently. What will happen then? Still I have only 1 instance of `mySuite` that can be access at the same time by 2 goroutines that running the 2 features?

Or Godog will create a new `mySuite` instance for each feature (in case of running concurrently)?

```feature
Feature: Registration
    Scenario: registration
        Given a valid profile
        When user send the request
        Then we must records the profile
            And the response code should be "200"
            And the user should be on "trial"
```
```feature
Feature: Chat
    Scenario: chat
        Given a valid chat message
        When user send the request
        Then we must records the chat
            And the response code should be "200"
```

**Comment by l3pp4rd** [comment]
Yes exactly, godog creates separate instances of mySuite for each parallel goroutine and the concurrency option is exactly limiting these instances
