### ISSUE TITLE
Supported Gherkin version

### ISSUE THREAD

**Issue by ramanvis** [DATA-DOG/godog#179]
Question: Does godog support Gherkin v6. I see in Readme that godog supports gherkin3. Is it same as gherkin version 3?

**Comment by l3pp4rd** [comment]
yes it is v3. the reason why it is not upgraded to v6 is the dependency of protobuf. I prefer that this library would not have any external dependencies. In later versions, there are some different keyword support and Rule keyword, which could be migrated at some point. But that will be done sometime later. Though, to resolve some concurrency issues you also referenced, the gherkin nodes should be linked by parent node or additional abstraction layer needs to be made. anyway, these all have something to do with gherkin. Sadly, I do not want the protobuf dependency for this library

**Comment by ramanvis** [comment]
Thanks for the prompt reply
