### ISSUE TITLE
Dynamic examples in a step

### ISSUE THREAD

**Issue by inluxc** [DATA-DOG/godog#184]
This is the example I'm using:

> Scenario: Create Order and Send Server
    Given Generate Order data
    Then Send order data to Server and Validate it

So in the first step, I obtain data from a BD and generate simulated order data and in the second one, I want to execute lots of times depending on the quantity generated by the first step.

How it possible to do this. 

I think we should get our selfs a Discord Server. For these types of requests.

**Comment by l3pp4rd** [comment]
Hi, the step definition is a dynamic function, you can do whatever you want in it. Calling apis as much times as you need is fine.
