### ISSUE TITLE
Getting "imported and not used" errors when I try to run tests for a main package

### ISSUE THREAD

**Issue by pmcgrath** [DATA-DOG/godog#20]
I have a feature and test file in the same directory as the main package for an application that I wanted to test, but when I run godog . it fails with a bunch of "imported and not used" errors.
One for each the import statements.

From looking at the code it seems there is an issue with the merge function where it does not remove all of the imports, which were needed for my main function.

In my case I have a single main function like your cmd/godog package which calls library type package functions but does some flags type parsing.

If I move the feature file and its test file to another directory it works, my use case is for running api tests.

I have been able to re-create by making two alterations to your api example @ https://github.com/DATA-DOG/godog/blob/master/examples/api/api.go

1) Add import "os"
2) Add the following at the top of the main function - serves no purpose, just to illustrate the failure
	fmt.Println(os.Getenv("PATH"))

Since the main method is removed and it does not remove the "os" import I get

**/tmp/1459347300796577005godog.go:11: imported and not used: "os"**

Thanks in advance
Pat

**Comment by l3pp4rd** [comment]
indeed, good point. needs to be resolved. thanks for pointing it out

**Comment by pmcgrath** [comment]
No problem and thanks again for this tool

**Comment by pmcgrath** [comment]
FYI - A hackety hack way I could get around this where my main function was the only function in the main package is to rename the main function to something like runMain which I then call from main.

**Comment by l3pp4rd** [comment]
yes, that would work. godog overwrites main func with its own to run tests, but it missed to recheck package dependencies
