### ISSUE TITLE
Use "features" instead of "examples" for `feature`-files-directory

### ISSUE THREAD

**Issue by dg-ratiodata** [DATA-DOG/godog#26]
@l3pp4rd Good morning, hope you're fine?

# Background

I'm going to write my second go app. I would like to see, if I can setup a similar `aruba`-thing in go we have with ruby.

# Current situation

You use the term `examples` for your feature directory in your README.md which I find confusing.

## Proposed change

Does it makes sense to change that to `features` instead? Event in `godog -h` you use the term `features`.

~~~bash
godog -h

# =>   godog [options] [<paths>]
# => 
# => Arguments:
# =>   paths:                Optional path(s) to execute. Can be:
# =>                             - dir (features/)
# =>                             - feature (*.feature)
# =>                             - scenario at specific line (*.feature:10)
# =>                         If no paths are listed, suite tries features path by default.
# => 
~~~

## Motivation

Having the same terms over all cucumbers make it easier for users to recognize things.

**Comment by l3pp4rd** [comment]
Hey @dg-ratiodata  yes that makes sense, thanks for noting and clarifying.
