### ISSUE TITLE
On a test fail a ctual exit status of the godog run is zero, although it outputs "exit status 1" as the last line of the log

### ISSUE THREAD

**Issue by anton-107** [DATA-DOG/godog#31]
Steps to reproduce:
- run a failing test with godog

Expected result:
- command line program exits with status 1

Actual result:
- i see "exit status 1" in the output
- the actual exit status is 0

**Comment by l3pp4rd** [comment]
hm, which OS are you running it with? I tested this behavior on linux, seemed OK. the point is that I use a common implementation to capture exit status, but it uses the syscall, which might not work for other oses.. if that would not be complicated, could you try to play with [few lines of source code](https://github.com/DATA-DOG/godog/blob/master/cmd/godog/main.go#L60) ?

**Comment by l3pp4rd** [comment]
maybe it does not determine an error as exit error, could you try changing [status](https://github.com/DATA-DOG/godog/blob/master/cmd/godog/main.go#L73) to 1

**Comment by l3pp4rd** [comment]
or to parse it from output, [change line](https://github.com/DATA-DOG/godog/blob/master/cmd/godog/main.go#L45) to `fmt.Fprintln(stderr, string(details))` would be helpful if you try these

**Comment by anton-107** [comment]
Sorry for this ticket, it seems like i was on the old version of godog (i was going through a quite complex setup due to my app using vendoring).

After the proper update of the godog and putting my steps definitions to a "_test.go" (looks like this wasn't required in 0.2.0)  it works as expected.

**Comment by l3pp4rd** [comment]
OK, good to know. concerning the setup, sadly using **gb** with godog requires custom setup. maybe in the future I'll have a look how this could be simplified.
