### ISSUE TITLE
Assistance with error

### ISSUE THREAD

**Issue by airomega** [DATA-DOG/godog#32]
Hi,

We have been using Godog for a while with no issues. I ran an update and now get the error:

```
# _/tmp/godog-1464349241273590437
godog_runner_test.go:13:29: expected ';', found 'IDENT' featureContext
godog_runner_test.go:16:2: expected '}', found 'EOF'
FAIL	_/tmp/godog-1464349241273590437 [setup failed]
```

The error message is very unclear and doesn't point to any of my feature or step files. Also, I absolutely did not change my working godog test code at all - the only change was running go get -u github.com/DATA-DOG/godog/cmd/godog.

Can you advise on how to resolve?

**Comment by l3pp4rd** [comment]
could you run `go get -u github.com/DATA-DOG/godog/cmd/godog` should be solved. introduced by mistake. was failing in context registration when there is more than one suite context

**Comment by l3pp4rd** [comment]
thanks for reporting it. will need to add regression test for this case

**Comment by airomega** [comment]
That's worked. Thanks for the quick turnaround.
