### ISSUE TITLE
reflect: Call using *gherkin.DocString as type *gherkin.DocString

### ISSUE THREAD

**Issue by tanmayambre** [DATA-DOG/godog#33]
After updating to latest godog all multiline string text started failing

eg. Feature
```
    When  I publish a message:
      """
      {
          "data": {
              "point1": 1,
              "point2": 2,
              "point3": 3
          }
      }
      """
```

Step Definition
```
func iPublishAMessage(input *gherkin.DocString) error {
	log.Println("Gherking", input, input.Content)
        //... Do publish
	return nil

}
```

The following error appears 
```reflect: Call using *gherkin.DocString as type *gherkin.DocString```

Is there something wrong here?

**Comment by tanmayambre** [comment]
Never Mind I found the mistake.I had to change my import path for gherkin to the on shipped with godog

**Comment by l3pp4rd** [comment]
yes, sorry for this breaking change, but this will be better for the future. there was one BC break introduced by gherkin before. Want to make sure it will always be compatible. Gherkin will be synced with the remote time to time. cheers
