### ISSUE TITLE
godog binary should support -h and/or --help

### ISSUE THREAD

**Issue by nightlyone** [DATA-DOG/godog#34]
As a user I would like to see what options I can pass to a binary so that I don't need to remember them all.

Usually this is accomplished by accepting -h or --help as parameters.

**Comment by l3pp4rd** [comment]
Currently -h or --help option is only triggered if there are buildable package sources. this should be fixed in the near future.

![2016-06-01-130631](https://cloud.githubusercontent.com/assets/132389/15705874/b2df7f62-27f9-11e6-9afe-bf7063583592.png)
