### ISSUE TITLE
--stop-on-failure doesn't stop

### ISSUE THREAD

**Issue by omnicolor** [DATA-DOG/godog#39]
I recently updated to v0.4.3 and noticed that adding the --stop-on-failure flag doesn't stop executing when a scenario fails.

**Comment by l3pp4rd** [comment]
thanks for noting, will need a test for it

**Comment by omnicolor** [comment]
Created the simplest test I could think of at https://github.com/omnicolor/godog-stop-on-failure

**Comment by l3pp4rd** [comment]
ah, you misunderstood me :) I've meant that I'll need to write a godog test scenario to prevent regression, cheers ;)
