### ISSUE TITLE
Panic in fmt_pretty

### ISSUE THREAD

**Issue by OwenGr** [DATA-DOG/godog#44]
Probably related to #42

Attempting to run godog in the godog code folder results in the following panic:

![image](https://cloud.githubusercontent.com/assets/12298985/16347293/24622542-3a09-11e6-9acd-2c1b100fac6d.png)

**Comment by l3pp4rd** [comment]
hi @OwenGr was it resolved by #42 ? it was merged to master.

**Comment by OwenGr** [comment]
No, it was not resolved by #42; this is with the updated code.

**Comment by l3pp4rd** [comment]
OK, thanks
