### ISSUE TITLE
Integrate with go test tool?

### ISSUE THREAD

**Issue by pyros2097** [DATA-DOG/godog#46]
Is is possible for me to run my features using the go test command?
I would like to have a test file with maybe a single test function which will invoke the godog runner command with a suite which is prepared by it. Then I wouldn't need to depend on the godog command to run my tests. I can just integrate it will all my other tests.

**Comment by l3pp4rd** [comment]
in general it is possible to [run it](https://github.com/DATA-DOG/godog/blob/master/run.go#L75) but it needs command line arguments. The argument is a function where you register your contexts. You probably can copy os.Args and modify them for the godog and set them back after running godog. I'll probably add an example later. I'd suggest you to use [TestMain](https://golang.org/pkg/testing/#hdr-Main) to run godog before or after go tests and setup database or whatever is necessary for your suite.

**Comment by pyros2097** [comment]
Anyway my boss implmented cucumber over the weekend for our test cases, Since he needed some features that were lacking.
Here's the link check it out it https://github.com/playlyfe/cucumber

**Comment by l3pp4rd** [comment]
what features were required in your case?

**Comment by pyros2097** [comment]
Backgrounds and Data tables
https://github.com/cucumber/cucumber/wiki/Scenario-outlines
https://github.com/cucumber/cucumber/wiki/Background

**Comment by l3pp4rd** [comment]
these are all supported.. [backgrounds](https://github.com/DATA-DOG/godog/blob/master/features/events.feature#L6) and [outlines](https://github.com/DATA-DOG/godog/blob/master/features/load.feature#L28). gherkin 3 is fully supported. the event stream is also currently being implemented in the pull request.. anyway, guess your boss wanted to simply rewrite it on his own :) cheers

**Comment by atrniv** [comment]
Hi @l3pp4rd, I've been facing a rather sticky problem when taking the approach you suggested to run go-dog from within tests. The issue is that go-dog uses the golang flags system which has a global state. This is conflicting with a logging package glog which also uses the flags system. I think it would be best to provide an alternative run API which will allow the running of go-dog using programmatic parameters instead of command line flags.

**Comment by l3pp4rd** [comment]
yes @atrniv I was thinking about it. will resolve it when I have time for it ;) moving this to #50

**Comment by l3pp4rd** [comment]
@atrniv resolved by #50
