### ISSUE TITLE
Color output appears off for steps in Scenario Outline mode

### ISSUE THREAD

**Issue by jeffgarratt** [DATA-DOG/godog#51]
When using scenario outlines with example tables the color for passed steps appears in skipped color.

**Comment by jeffgarratt** [comment]
And thank you for this library, porting over from Behave (Python) and reused feature files easily

**Comment by jeffgarratt** [comment]
Ahhh, perhaps this is not an issue, seems as though you mark the example entry with the proper color.  The python behave version spits out a different report per example run for the scenario outline, allowing you to see the result color per example.

**Comment by l3pp4rd** [comment]
Hi, good to hear you find it helpful. I'm sure there may be some differences or even small bugs in the output, I will have a look into examples, could you give me a screenshot of the output?
