### ISSUE TITLE
godog does not print stack trace when panic is caught

### ISSUE THREAD

**Issue by upayavira** [DATA-DOG/godog#54]
Having used Behave (python) and Cucumber (Java), I really appreciate Godog, which I have integrated into a Go project.

I have one problem with it: When a problem occurs (especially an error raised), only the message is displayed, leaving me with no idea where the issue actually occurred:

```
runtime error: index out of range
```

Is there a way to tell godog to be more verbose so I can work out what index was out of range?

**Comment by l3pp4rd** [comment]
Hi, thanks. That is something what needs to be improved. Currently caught panics does not print stack trace, which needs to be changed. probably an error should have a different type similar to https://github.com/pkg/errors so it could print stack trace in verbose mode on %+v

Currently what I suggest you to do, is catch panic in your step in order to debug the reason. Later when I have some more time, I will revisit this. The issue is important but not critical to behavior. Thanks for reminding.

**Comment by upayavira** [comment]
Thx @l3pp4rd , how do I print a stack trace if all print statements are swallowed?

**Comment by l3pp4rd** [comment]
to replicate it, lets simply create a small feature:

``` gherkin
Feature: panic

  Scenario: panics
    Then fail with panic
```

Now implement the panic step in **_test.go** file.

``` go
package main

import (
	"fmt"

	"github.com/DATA-DOG/godog"
)

func myStepCallsFunc() {
	arr := make([]int, 0)
	fmt.Println(arr[6])
}

func failWithPanic() error {
	myStepCallsFunc()
	return nil
}

func FeatureContext(s *godog.Suite) {
	s.Step(`^fail with panic$`, failWithPanic)
}
```

Run it:

![2016-10-06-071846](https://cloud.githubusercontent.com/assets/132389/19140393/65f82b72-8b95-11e6-823f-722871693a23.png)

Then lets print stack trace of panic instead.

``` go
package main

import (
	"fmt"
	"runtime/debug"

	"github.com/DATA-DOG/godog"
)

func myStepCallsFunc() {
	arr := make([]int, 0)
	fmt.Println(arr[6])
}

func failWithPanic() (err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("runtime error: %s", r)
			debug.PrintStack()
		}
	}()
	myStepCallsFunc()
	return
}

func FeatureContext(s *godog.Suite) {
	s.Step(`^fail with panic$`, failWithPanic)
}
```

And you see the output now:

![2016-10-06-073310](https://cloud.githubusercontent.com/assets/132389/19140624/5fe6cd7c-8b97-11e6-9e2f-b0473bafeddf.png)

**Comment by upayavira** [comment]
The simple answer is to use "log" which still outputs. Apologies for the noise.
