### ISSUE TITLE
code coverage?

### ISSUE THREAD

**Issue by gliptak** [DATA-DOG/godog#56]
Would you be interested in a code coverage PR? The numbers are very low:

https://codecov.io/gh/gliptak/godog/branch/codecov1

Maybe I'm missing some test executions?

**Comment by l3pp4rd** [comment]
godog is tested by godog, it was not using go test command to run features by default, since I need to test the godog command itself.

The actual coverage: https://codecov.io/gh/DATA-DOG/godog/branch/codecov

**Comment by gliptak** [comment]
Thanks for the pointer. Wrapping the ```godog``` run into a unittest is a good way to bring it under a single umbrella.

**Comment by gliptak** [comment]
@l3pp4rd Are you merging ```codecov``` to ```master``` soon? Thanks

**Comment by l3pp4rd** [comment]
yes, have added it in master

**Comment by gliptak** [comment]
Thx
