### ISSUE TITLE
Output when using go test

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [DATA-DOG/godog#68]
When using `go test` to run godog features as described in the readme (using
`TestMain`), when the tests are successful, I don't get any output about which
features / steps are run in case of success, but I do get output for example
from a gin http server running as part of the test suite.

Is this intended behavior?

**Comment by l3pp4rd** [comment]
Hi, depends on what exactly are you seeing, for example **godog** itself has a test suite integrated in **TestMain** with a `progress` format. So when you run it:

![2017-03-21-130539](https://cloud.githubusercontent.com/assets/132389/24144787/3d3563b0-0e37-11e7-878b-ae1d93292377.png)

Note, you do not see the exact scenarios printed since it is a **progress** format. If you change it to **pretty** then you will get all details.

``` go
func TestMain(m *testing.M) {
	status := RunWithOptions("godog", func(s *Suite) {
		SuiteContext(s)
	}, Options{
		Format:      "pretty",
		Paths:       []string{"features/load.feature:22"}, // only one scenario for this example
	})

	if st := m.Run(); st > status {
		status = st
	}
	os.Exit(status)
}
```
![2017-03-21-131103](https://cloud.githubusercontent.com/assets/132389/24144947/ebb6a82c-0e37-11e7-865d-bab90842b807.png)

That is the intended behavior. If you are seeing different things then give me more context about your environment..

**Comment by valentin-krasontovitsch** [comment]
Thanks for the prompt feedback, very helpful!
Indeed my setup was using the format `progress`, and I'm getting all the desired output when using `pretty`.

I also just noticed that I was a bit imprecise:

I'm actually using `go test $(glide novendor)` to run the test suite without running tests that might be included in vendored packages in the subfolder `vendor/`. In my case, the project is very simple, so `glide novendor` just returns `.` - and running `go test .` gives me just
```
ok      gitlab.knf.local/ngs/gpp        0.015s [no tests to run]
```
The no tests to run is due to the fact that I only have features, and just have a `TestMain` that runs those features. But even when I add a dummy test, I still have the same output behavior: Just one line when I call `go test .`

Running `go test` gives me all the desired output. Running `go test -v .` also solves the problem, i.e. I get all the output I need without running tests I don't want to run.

Was just wondering if anybody had an explanation for the difference in output behavior of `go test` when called with a directory, and when called on its own.

As this is actually a question about `go test`, I'm gonna go ahead and close the issue.

**Comment by valentin-krasontovitsch** [comment]
Turns out that this is normal behavior - `go test .` tests the package found in `.` and testing packages prints out a summary for each package, which in the case of one package results in a one-liner... got this answer on [Stackoverflow](http://stackoverflow.com/questions/42972827/difference-in-output-when-calling-go-test-with-package).

**Comment by l3pp4rd** [comment]
thanks for getting back with the answer reference, might be useful for someone else. If there would be a failure in package while running `go test .` then you would get detailed error, see bellow.

![2017-03-23-144356](https://cloud.githubusercontent.com/assets/132389/24248222/460f0116-0fd7-11e7-826f-8870c3f1be43.png)
