### ISSUE TITLE
Create an assist package

### ISSUE THREAD

**Issue by rdumont** [DATA-DOG/godog#72]
I have used SpecFlow, the Gherkin implementation for .NET, for many years. Since moving to Go, and starting using Godog, there are a few things that I miss from SpecFlow. The greatest of all is the equivalent of the [assist helpers](http://specflow.org/documentation/SpecFlow-Assist-Helpers/).

I'd like to take a shot at starting an `assist` package that could fulfill such needs, starting with these two simple functions that might make it easier to work with tables. Is there already something like it that I didn't see?

### `ParseInstance`

Step:
```gherkin
Given the user
  | First Name | John |
  | Last Name  | Doe  |
  | Age        | 35   |
```

Implementation:
```go
user := assist.ParseInstance(table)
// user["First Name"] == "John"
// user["Last Name"] == "Doe"
// user["Age"] == 35
```

### `ParseSlice`

Step:
```gherkin
Given these users
  | First Name | Last Name | Age |
  | John       | Doe       | 35  |
  | Gwen       | Stacy     | 22  |
```

Implementation:
```go
users := assist.ParseSlice(table)
// len(users) == 2
// users[0]["First Name"] == "John"
// users[1]["First Name"] == "Gwen"
```

**Comment by l3pp4rd** [comment]
Hi, good to know you found godog.

Regarding something similar to assist, I think it is too broad to integrate in godog library. I see that SpecFlow uses generics in order to map compare table data to domain objects. Integrating something like that in godog, would span such feature requirements like field tags in order to map it through reflect package and etc. While it is possible to implement such features, but in general, I do not see this as a core feature, because these are just helper functionality and seeing it in core library adds more to learning curve. Instead I would like users implementing something like that in their test suites or using third party extensions.

I would certainly reference that package in readme and examples if you create such, so users could find it easily if they were looking for functionality like that out of the box.

**Comment by rdumont** [comment]
@l3pp4rd, makes sense, so I'm going to implement these features in another repo. You may close this issue if you'd like, and I'll get back to you with a link to the repo when I have something. Thanks :)

**Comment by l3pp4rd** [comment]
great, I'll leave it open, maybe we get some more interest or feedback from other users ;)

**Comment by maxmeyer** [comment]
@rdumont Any progress on your library? @l3pp4rd What's your preferred way to transform the table into something more easier to use?

For now I use something like the code below to turn the `DataTable` into something usable. This requires to have a struct which has "setter"-methods - `func Set<ColumnName>` attached to it.

`items/item.go`:

~~~go
package items

type TripItems struct {
	Items []Item
}

type Item struct {
	Name             string   `toml:"name"`
	Description      string   `toml:"description"`
}

func (i *Item) SetName(text string) {
	i.Name = text
}

func (i *Item) SetDescription(text string) {
	i.Description = text
}
~~~

`godogs_test.go`:
~~~go
func aListOfItemsForTheActivity(activity string, itemTable *gherkin.DataTable) error {
	var knownItems items.TripItems

	head := itemTable.Rows[0].Cells

	for i := 1; i < len(itemTable.Rows); i++ {
		item := items.Item{}
		rItem := reflect.ValueOf(&item)

		for n, cell := range itemTable.Rows[i].Cells {
			methodName := "Set" + strings.Title(head[n].Value)
			method := rItem.MethodByName(methodName)

			if method.IsValid() {
				method.Call([]reflect.Value{reflect.ValueOf(cell.Value)})
			} else {
				return errors.Wrap(ErrTableHeaderError, head[n].Value)
			}
		}

		knownItems.Items = append(knownItems.Items, item)
	}

	var buf bytes.Buffer
	enc := toml.NewEncoder(&buf)
	err := enc.Encode(knownItems)

	if err != nil {
		return err
	}

	b := []byte(buf.String())

	os.RemoveAll(WorkingDirectory())
	os.MkdirAll(WorkingDirectory(), 0755)
	filePath := filepath.Join(WorkingDirectory(), "db.toml")

	err = ioutil.WriteFile(filePath, b, 0644)

	if err != nil {
		return err
	}

	return nil
}
~~~

**Comment by l3pp4rd** [comment]
Hi @maxmeyer well I suggest to have a type for such transformations:

``` go
type MyTable *gherkin.Table

func (t MyTable) RowsSet() [][]string {...} // extracts 2D array of rows and their columns

func (t MyTable) MapRows(to interface{}) error // uses reflect with whatever field conventions you prefer

// then the usage

func godogStep(table *gherkin.Table) error {
    type Item struct {
	Name             string
	Description      string
    }

    var items []item
    if err := MyTable(table).MapRows(&items); err != nil {
        return err
    }

    // work with items...
   return nil
}
```

I personally prefer having conventions for field mapping instead of using field tags. For example the usual is **snake case** or **underscore**. If you are making such table mapper as a library. then it would make sense to provide an option for field mapping strategy:

``` go
type FieldNameMapper func(string) string

var SnakeCaseMapper FieldNameMapper = func(src String) string {
        thisUpper := false
	prevUpper := false

	buf := bytes.NewBufferString("")
	for i, v := range src {
		if v >= 'A' && v <= 'Z' {
			thisUpper = true
		} else {
			thisUpper = false
		}
		if i > 0 && thisUpper && !prevUpper {
			buf.WriteRune('_')
		}
		prevUpper = thisUpper
		buf.WriteRune(v)
	}
	return strings.ToLower(buf.String())
}

func (t MyTable) MapRows(to interface{}, fnm FieldNameMapper) error
```

Which would transform every struct field to column name.

It all depends on your use cases, I've shown more common use cases, your custom table type may have any number of methods to map the table in preferred ways

**Comment by maxmeyer** [comment]
@l3pp4rd Thanks a lot. Is there any documentation / blog post were you explained that in more detail? As this seems to be a quite common task, does it make sense to have some kind of documentation for that? Do you know Cucumber.Pro? It might be worth to push your docs there. @mattwynne Gave us a short introduction on CukenFest. To give you an idea how the docs look like, have look at the [aruba one's](https://app.cucumber.pro/projects/aruba).

**Comment by maxmeyer** [comment]
I like the idea to have a separate mapper type. So everything is cleanly encapsulated.

**Comment by l3pp4rd** [comment]
Hi, well I'm quite busy with other projects at the moment, but I may put it into some of the examples later on. It would be easier to maintain a single repository instead of a few places.

**Comment by rdumont** [comment]
Hello, guys! Sorry for the delay here. The library has finally come to life, as [AssistDog](https://github.com/hellomd/assistdog). Please see the [documentation for examples](https://godoc.org/github.com/hellomd/assistdog#pkg-examples). Contributions are welcome!

@l3pp4rd, feel free to add a link to it in your documentation if you'd like. AssistDog still has a lot to be improved, expecially when it comes to documentation, and its API is still unstable. But I believe that it is already a great start.

**Comment by maxmeyer** [comment]
@rdumont Thanks a lot. This is quite helpful.
