### ISSUE TITLE
panic: strings: negative Repeat count

### ISSUE THREAD

**Issue by ehames** [DATA-DOG/godog#85]
When running godog concurrently with pretty formatter, I get the following error:

panic: strings: negative Repeat count
goroutine 8 [running]:
strings.Repeat(0x1433758, 0x1, 0xfffffffffffffffa, 0xc4201b4240, 0x3c)
	/usr/local/go/src/strings/strings.go:432 +0x258
github.com/DATA-DOG/godog.s(0xfffffffffffffffa, 0x13a2300, 0xc420010ff0)
	/Users/edgardo/src/github.com/DATA-DOG/godog/utils.go:28 +0x40
github.com/DATA-DOG/godog.(*pretty).printStep(0xc4200a3540, 0xc420010ff0, 0xc420156b60, 0x144b208)
	/Users/edgardo/src/github.com/DATA-DOG/godog/fmt_pretty.go:236 +0x55c
github.com/DATA-DOG/godog.(*pretty).printStepKind(0xc4200a3540, 0xc4201b41c0)
	/Users/edgardo/src/github.com/DATA-DOG/godog/fmt_pretty.go:311 +0xac
github.com/DATA-DOG/godog.(*pretty).Passed(0xc4200a3540, 0xc420010ff0, 0xc420156b60)
	/Users/edgardo/src/github.com/DATA-DOG/godog/fmt_pretty.go:334 +0x143
github.com/DATA-DOG/godog.(*Suite).runStep.func1(0xc420049d88, 0x0, 0x0, 0xc4200ea1e0, 0xc420010ff0, 0xc420049d30)
	/Users/edgardo/src/github.com/DATA-DOG/godog/suite.go:233 +0x21f
github.com/DATA-DOG/godog.(*Suite).runStep(0xc4200ea1e0, 0xc420010ff0, 0x0, 0x0, 0x0, 0x0)
	/Users/edgardo/src/github.com/DATA-DOG/godog/suite.go:272 +0x243
github.com/DATA-DOG/godog.(*Suite).runSteps(0xc4200ea1e0, 0xc42014a380, 0x4, 0x4, 0x0, 0x0, 0x1, 0xc4200fdba0)
	/Users/edgardo/src/github.com/DATA-DOG/godog/suite.go:341 +0x7d
github.com/DATA-DOG/godog.(*Suite).runScenario(0xc4200ea1e0, 0xc42008f200, 0x0, 0x1, 0xc4200fdba0)
	/Users/edgardo/src/github.com/DATA-DOG/godog/suite.go:472 +0x118
github.com/DATA-DOG/godog.(*Suite).runFeature(0xc4200ea1e0, 0xc420142750)
	/Users/edgardo/src/github.com/DATA-DOG/godog/suite.go:447 +0x539
github.com/DATA-DOG/godog.(*Suite).run(0xc4200ea1e0)
	/Users/edgardo/src/github.com/DATA-DOG/godog/suite.go:190 +0xa9
github.com/DATA-DOG/godog.(*runner).concurrent.func1(0xc42013f9d0, 0xc4200dd0c0, 0xc4200fdbfe, 0xc420142750)
	/Users/edgardo/src/github.com/DATA-DOG/godog/run.go:40 +0x134
created by github.com/DATA-DOG/godog.(*runner).concurrent
	/Users/edgardo/src/github.com/DATA-DOG/godog/run.go:44 +0x101

Please, let me know if you need any further input.

**Comment by l3pp4rd** [comment]
Hi, guess you were running it with concurrency option, please pull the recent changes, there is a restriction and only progress format supports concurrency in general.

**Comment by ehames** [comment]
Thanks, I saw the restriction in the docs but got the error anyway so I considered reporting it. It is indeed fixed in master (my bad, I thought I was running the latest code).

**Comment by l3pp4rd** [comment]
that's fine, there were no tests covering this part, but added with a patch together in order to prevent such regression in the future. cheers ;)
