### ISSUE TITLE
windows bug with color output when integrated with testrunner

### ISSUE THREAD

**Issue by mroth** [DATA-DOG/godog#87]
This is a weird one I encountered when working on testing my steps to be cross-platform in a Windows VM.

This is for godog tests integrated into TestMain so they can be run via `go test`. Refer to the following screenshot:
![win10_color](https://cloud.githubusercontent.com/assets/40650/26609798/54215766-4571-11e7-96fc-ce0253a5978d.PNG)

The bottom example was called with `go test`.  The top example was called with `go test .`  (minimal pkg specification for current package).

I'm not sure what's going on here, but it appears that whenever go test is invoked with an actual package specification, something changes that interferes with how godog is selecting its color output, so it is no longer outputting in Windows-compatible mode.

This issue is somewhat compounded in that the most-common way to run tests in a multi-package project is with `go test ./...` which also triggers this bug.

(I don't actually normally develop on Windows, so I may be missing something obvious here.)

**Comment by l3pp4rd** [comment]
Hi, yes indeed, in first example I see that color codes were not converted to windows compatible format. Currently godog always [colors the Output](https://github.com/DATA-DOG/godog/blob/master/run.go#L105) where the colorization writer is determined by whether it is windows or not. I do not actually see where the issue might be, because the **colors** package when compiled, is always compiled for correct architecture.

It seems like Colored was not called on this output writer. Maybe `go test` somehow replaced the **os.Stdout**. you could try to print the pointer reference for os.Stdout in godog Run command and in tested package main function.

**Comment by mroth** [comment]
Hmm, not sure if I'm doing something wrong, but using `fmt.Println("ADDRESS OF STDOUT:", &os.Stdout)`, I seem to get the same address `0x1439a50` whether called in TestMain, godog.Run, or in a BeforeScenario hook. (testing on my Darwin workstation, but that portion shouldn't differ based on GOOS I believe).

**Comment by l3pp4rd** [comment]
have you tried that on windows? because on linux `go test`, `go test .` and `go test ./...` prints valid output. I'll try to setup windows vm when I have more time to try to figure this one out

**Comment by mroth** [comment]
> have you tried that on windows? because on linux go test, go test . and go test ./... prints valid output. I'll try to setup windows vm when I have more time to try to figure this one out

Yeah, just tested in a VM -- looks like the address is the same.

Another clue I've noticed is that output is "instant" (e.g. continuously outputted to STD) with `go test`, but `go test PKGSPEC` will buffer the output and send it all at once (on all platforms). This makes me suspect that go test might be somehow wrapping the output in the multi-pkg case (which it enters even if only one package is specified?), and this output buffering is somehow interfering with the color codes on Windows?

EDIT: Yeah, I'm pretty sure that buffering is occurring -- as `go test` does parallel builds and tests for multiple packages by default, so it would make sense that it would need to buffer the output for each so that the output wouldn't overlap.

**Comment by l3pp4rd** [comment]
if for example I set option NoColor. in linux it works just fine when you run multi package tests. So this could only mean that in windows something different is happening. maybe next week I'll have some more spare time to see it in windows VM.

I see in [go test](https://github.com/golang/go/blob/master/src/cmd/go/internal/test/test.go#L1168) implementation that it buffers output for separate packages, and each package is run as a separate command, then finally the output is combined.

But what we see in your example, is that it prints linux color codes, maybe it means the colors package included in test package, was compiled as a non windows OS package or something is wrong with the screeninfo, try to print something [here](https://github.com/DATA-DOG/godog/blob/master/colors/ansi_windows.go#L171) and see whether the number of times in screen is the same as number of packages tested. and maybe check if screeninfo is similar.

**Comment by l3pp4rd** [comment]
I've made a windows VM and seems like it is indeed related to buffered output, just so far cannot find the reason why it does not color it, because the output bytes are exactly the same. will need to try different colorization libraries to check whether there is a difference

**Comment by l3pp4rd** [comment]
tried this also with https://github.com/mattn/go-colorable same issue. but I noticed it only in command prompt. If you use MsysGit bash client for windows it works fine. This is hard to determine whether this is an issue how go test operates or somewhere else, but that does not look that colorization library has way to solve it.

**Comment by l3pp4rd** [comment]
closing in favor of #129
