### ISSUE TITLE
Enhancement of the error message of the gherkin parser

### ISSUE THREAD

**Issue by Dogild** [DATA-DOG/godog#90]
With the current version, the gherkin parser does not give a helpful error when having a gherkin syntax error.

For instance when having the steps (missing quotes) :

```cucumber
    Given root creates a new namespace through the api namespaces with the data:
    """
    {
      "name" : "5a742e56-8faa-4346-a1e8-05504ee6df0e_3",
      "associatedTags" : ["namespace=/5a742e56-8faa-4346-a1e8-05504ee6df0e_2"]
    }
    ""
```

godog will return the following error:
```
2017/06/13 14:35:51 Parser errors:
(102:0): unexpected end of file, expected: #DocStringSeparator, #Other
```

it could be helpful to have more informations about the error like the feature file, steps concerned etc etc...Right now, it gets very complicated to know where the error comes from when refactoring lot of features.

Thanks

**Comment by l3pp4rd** [comment]
Hm, indeed, will need to add a feature file path to error message
