### ISSUE TITLE
Scenario Outline example values not populating DataTable

### ISSUE THREAD

**Issue by henry-young** [DATA-DOG/godog#92]
Scenario Outline example values do not seem to work correctly with DataTables. 

What I expect to happen: 
`<value>` tokens in the DataTable are replaced by the values found in the Example table.

What actually happens: 
Token replacement is not happening and the actual `<value>` string is populated in the DataTable cell.

Take the following feature for example:
```gherkin
Scenario Outline:
    Given a user with the values
      | key       | value       |
      | firstName | <firstName> |
      | lastName  | <lastName>  |
      | age       | <age>       |
    When a color is selected for them
    Then the result should be "<result>"
  Examples:
    | firstName | lastName | age | result |
    | john      | doe      | 18  | red    |
    | jane      | doe      | 21  | blue   |
```

in the _test.go file
```go
func aUserWithTheValues(table *gherkin.DataTable) error {
    log.Println(table.Rows[1].Cells[1])
    return nil
}
```
The function should print either `"john"` or `"jane"`, but it will always print `"<firstName>"`.

**Comment by l3pp4rd** [comment]
Yes indeed, will have a look after vacation, thanks for reporting
