### ISSUE TITLE
Log output

### ISSUE THREAD

**Issue by varas** [DATA-DOG/godog#93]
It would be great to have `log.Print` output supported.
The output is suppressed at least when used under go test runner integration.

**Comment by varas** [comment]
My fault

**Comment by l3pp4rd** [comment]
Hi, it may be tricky, since go test does buffer the output when you run `go test` if it fails it prints it, but if it does not, then it may not print anything. see [this](https://stackoverflow.com/questions/23205419/how-do-you-print-in-a-go-test-using-the-testing-package) for more details.
