### ISSUE TITLE
hide step location comment in pretty output

### ISSUE THREAD

**Issue by JeanMertz** [DATA-DOG/godog#96]
```
  Background: Prepare Kafka
    Given the topic "process-test" exists # step_test.go:34 -> *Run.github.com/blendle/go-streamprocessor.theTopicExists
```

We run our suite off of a struct that contains some cross-step data for the entire suite. This makes the line details after the step itself in the "pretty" output mode quite verbose and long, going over into multiple lines, making the output harder to read.

It would be nice if either 1) it did not have this behaviour in this specific situation (and thus show the shorter output), or 2) an option exists to remove the `# steps_test.go....` details entirely from the output, making for a cleaner and more easily parsable output.

**Comment by l3pp4rd** [comment]
Hi, guess this could be shortened like:

``` gherkin
  Background: Prepare Kafka
    Given the topic "process-test" exists # step_test.go:34 -> *Run.theTopicExists
```
Because everyone will probably know which package it executed in. So far it might not need `--verbose` flag
