### ISSUE TITLE
Substep error should indicate which substep has failed

### ISSUE THREAD

**Issue by Dogild** [DATA-DOG/godog#98]
Hi,

Right now when using the `Substep` feature with the object `godog.Steps`, it's getting a bit complicated to know which substep has failed (no hook or no call to the formatter).

For instance, when having 

```
    Then I launch the following steps:
      """
      ->I launch a processing unit nginx 
      ->I launch a processing unit centos
```

Good will only say that the step `Then I launch the following steps` has failed, which is true but wrong due to a lack of granularity

Thanks,

**Comment by l3pp4rd** [comment]
Hi, we could prepend failed step text to the error in case if it was a substep. In result you could have something like `I launch a processing unit nginx: failed to start container` as an error message. does it make sense?

**Comment by Dogild** [comment]
It makes sense! 

I had the idea to do that in my private fork, however I didn't do it since I believe the formatter should be responsible to format any message.

So instead of doing that, I call the method `Failed` of the formatter, like this :

``` golang
func (s *Suite) maybeSubSteps(result interface{}) error {
	if nil == result {
		return nil
	}

	if err, ok := result.(error); ok {
		return err
	}

	steps, ok := result.(Steps)
	if !ok {
		return fmt.Errorf("unexpected error, should have been []string: %T - %+v", result, result)
	}

	for _, text := range steps {
                       def := s.matchStepText(text.(string))
                       def.IsSubstep = true
                       if def == nil {
				return ErrUndefined
			} else {
				if err := s.maybeSubSteps(def.run()); err != nil {
                                        step := &gherkin.Step{Text: text.(string)} // TODO: a bit light, need location etc etc
					s.fmt.Failed(step, def, err)
					return err
				}
			}
	}
	return nil
}
```

This is not perfect, but it adds th possibility to do whatever you want with the substep in the formatter.
The only API changed was to add `IsSubstep` and change `nested` to `Nested` to `StepDef` (have something symmetric).

**Comment by l3pp4rd** [comment]
Yes, it would work. but fmt.Failed will produce an entry in different formats, though I treat multistep as single step. because it actually is a single step in gherkin definition. what multistep allows to do is to combine steps instead of calling their respective functions in go code and checking errors yourself.
