### ISSUE TITLE
[Qusetion] Is there any way to sequence the tagging explicitly in multiple feature file

### ISSUE THREAD

**Issue by amitkrout** [DATA-DOG/godog#99]
I have more than one feature file and each feature file comprises feature specific scenarios. For example 
```
F1.feature
- S1
- S2
- S3
F2.feature
- S1
- S2
- S3

...
```
Now i want to select a sequence of ```F1(S1) -> F2(S1) -> F2(S2) -> F1(S2) -> F1(S3) -> F2(S3)``` in a single run.
Is there any way to do it ?

**Comment by l3pp4rd** [comment]
yes, call godog this way:

``` bash
godog F1.feature:5 F2.feature:5 F1.feature:13

# example from godog package
godog features/load.feature:6 features/multistep.feature:6 features/load.feature:23 features/multistep.feature:23
```

All godog arguments are feature file paths, you may specify separate scenarios at specific lines to be run in specific order. Note, that if you have a hook like `BeforeFeature` then it will be run separately for every specified feature in argument.
